#! /usr/bin/env bash


if [ -z "$1" ]; then
  echo "A variável tem valor!"
    exit 1
fi

BUCKET_NAME=$1

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket --bucket $BUCKET_NAME --create-bucket-configuration="LocationConstraint=eu-central-1"