#! /usr/bin/env bash
echo "==  Delete Bucket=="


if [ -z "$1" ]; then
  echo "A variável tem valor!"
    exit 1
fi

BUCKET_NAME="m-buck-pds123"

aws s3api delete-bucket --bucket $BUCKET_NAME --output text


