#! /usr/bin/env bash
echo "== List objects"

if [ -z "$1" ]; then
  echo "A variável tem valor!"
    exit 1
fi

BUCKET_NAME="bucket-pds-1-pt"

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api list-objects --bucket $BUCKET_NAME

